=== easyandeasy/myExample/mystruts/WebRoot/WEB-INF/mystruts-config.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT mystruts-config (action-mappings)>
<!ELEMENT action-mappings (action*)>
<!ELEMENT action (forward*)>
<!ELEMENT forward EMPTY>


<!ATTLIST action
	path CDATA #REQUIRED
	type CDATA #REQUIRED
	redirect (true | false) #IMPLIED
>

<!ATTLIST forward 
	name CDATA #REQUIRED
	path CDATA #REQUIRED
>

=== easyandeasy/myExample/mystruts/WebRoot/WEB-INF/mystruts-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mystruts-config SYSTEM "mystruts-config.dtd">
<mystruts-config>
	<action-mappings>
		<action path="login" type="com.mystruts.servlet.LoginServlet" redirect="true">
			<forward name="success" path="manager.jsp" />
			<forward name="failed" path="login.jsp" />
		</action>
		
		
		<action path="register" type="com.mystruts.servlet.RegisterServlet" redirect="true">
			<forward name="success" path="manager.jsp" />
			<forward name="failed" path="register.jsp" />
		</action>
	</action-mappings>
</mystruts-config>




























<!-- <mystruts-config>
	<action-mappings>
		<action path="login" type="com.mystruts.servlet.LoginServlet" redirect="true">
			<forward name="success" path="manager.jsp" />
			<forward name="failed" path="login.jsp" />
		</action>
		
		<action path="register" type="com.mystruts.servlet.RegisterServlet" redirect="true">
			<forward name="success" path="manager.jsp" />
			<forward name="failed" path="register.jsp" />
		</action>
	</action-mappings>
</mystruts-config> -->
